### ISSUE TITLE
Live preview in Firefox

### ISSUE THREAD

**Issue by bhansconnect** [mechanize-systems/bqnpad#3]
Hi, I noticed that live preview was just disable in firefox. Is it possible that this could still be left as toggle-able even it if is off by default? I use bqnpad specifically for the live preview, so it is very sad that the feature is suddenly not available in my browser.

**Comment by andreypopp** [comment]
Alright, made it off by default instead of disabling it. Sorry for that. Hope that FF will add support for Worker with ES modules soon.
